#!/usr/bin/env bash
# Quick setup checklist for Cloudflare + Two Server Setup
# This script provides commands and checks, but doesn't automate everything

set -euo pipefail

echo "=== Slipstream Cloudflare Setup Checklist ==="
echo ""
echo "SERVER MACHINE SETUP:"
echo "1. Generate TLS certificate:"
echo "   openssl req -x509 -newkey rsa:2048 -nodes \\"
echo "     -keyout key.pem -out cert.pem -days 365 \\"
echo "     -subj \"/CN=slipstream.yourdomain.com\""
echo ""
echo "2. Configure firewall (UDP 53 or 8853):"
echo "   sudo ufw allow 53/udp"
echo "   # OR for non-privileged port:"
echo "   sudo ufw allow 8853/udp"
echo ""
echo "3. Start target service (for testing):"
echo "   python3 scripts/interop/tcp_echo.py --listen 127.0.0.1:5201 &"
echo ""
echo "4. Run slipstream-server:"
echo "   # Standard DNS port (requires root):"
echo "   sudo ./target/release/slipstream-server \\"
echo "     --dns-listen-port 53 \\"
echo "     --target-address 127.0.0.1:5201 \\"
echo "     --domain slipstream.yourdomain.com \\"
echo "     --cert ./cert.pem \\"
echo "     --key ./key.pem"
echo ""
echo "   # OR non-privileged port:"
echo "   ./target/release/slipstream-server \\"
echo "     --dns-listen-port 8853 \\"
echo "     --target-address 127.0.0.1:5201 \\"
echo "     --domain slipstream.yourdomain.com \\"
echo "     --cert ./cert.pem \\"
echo "     --key ./key.pem"
echo ""
echo "CLOUDFLARE DNS CONFIGURATION:"
echo "1. Go to Cloudflare Dashboard > DNS"
echo "2. Add A record:"
echo "   - Type: A"
echo "   - Name: slipstream (or your subdomain)"
echo "   - IPv4: <your-server-ip>"
echo "   - Proxy: DNS ONLY (gray cloud) ⚠️ IMPORTANT"
echo "   - TTL: Auto"
echo ""
echo "CLIENT MACHINE SETUP:"
echo "1. Configure firewall (TCP 7000 or your port):"
echo "   sudo ufw allow 7000/tcp"
echo ""
echo "2. Run slipstream-client:"
echo "   # Using Cloudflare DNS:"
echo "   ./target/release/slipstream-client \\"
echo "     --tcp-listen-port 7000 \\"
echo "     --resolver 1.1.1.1:53 \\"
echo "     --domain slipstream.yourdomain.com"
echo ""
echo "   # OR using server IP directly:"
echo "   ./target/release/slipstream-client \\"
echo "     --tcp-listen-port 7000 \\"
echo "     --resolver <server-ip>:53 \\"
echo "     --domain slipstream.yourdomain.com"
echo ""
echo "TESTING:"
echo "1. Test DNS resolution:"
echo "   dig @1.1.1.1 slipstream.yourdomain.com"
echo ""
echo "2. Test connection:"
echo "   echo 'Hello' | nc <client-ip> 7000"
echo ""
echo "3. Monitor DNS traffic on server:"
echo "   sudo tcpdump -i any -n udp port 53"
echo ""
echo "TROUBLESHOOTING:"
echo "- Verify Cloudflare proxy is DISABLED (gray cloud)"
echo "- Check firewall rules on both machines"
echo "- Verify DNS A record points to correct server IP"
echo "- Test DNS resolution from client machine"
echo "- Check server logs for connection errors"
echo ""
echo "For detailed instructions, see: docs/cloudflare-setup.md"
